NAME:Swara Patel
Roll No.:18BCE172
Sessional Examination

A government wants to automate the admission process in all engineering colleges. A
government collected all relevant data and store it in CSV file. The format of the CSV file is
mentioned below.
College_details.csv file has information of courses offered by colleges:

The first line in the file is header, which have title of the columns like college code and short
form of engineering branches. In this file, from second line onwards, the college code and no
of seats available for each engineering branch is mentioned.
Constrains:
CollegeCode First character is C and remaining 4
characters are 4 digit randomly generated
number

No of seat for each branch Select values from below list
[0,60,120,180,240]

Second file is studentdetails.csv which has information about the students result and their
enrolment key.

As per sample given in above image, the first line is header of each column and second line
has student detail like student enrolment key and 5 subject marks.
Enrollmentno First character is E and remaining 4
characters are 4 digit randomly generated
number

Marks Generate the random number from the

range of 40 to 100

CollegeCode, CSE, IT, ME, EE, EC, IC, CH, Civil, Auto
C0001, 240, 120, 240, 60, 60, 60, 60, 0, 0

Enrollmentno, sub1, sub2, sub3, sub4, sub5
E0001, 87,98,65,50,78,86

Third file has choice_filling.csv which has student admission choice details that includes
enrolment number, college code and short form of branch. Format for the same is given
below.

As per sample given in above image, the first line has title of each value and second line
onwards, the choice data of each students is stored, which includes the studentâ€™s enrolment
key and 10 preferable CollegeID-Branch code in which he/she likes to take admission. While
giving a choice details, students have to provide CollegeID and short form of Branch. Verify
that college code is available in college details file. Also, verify which ever the branch choice
given by student is offered by college or not.
Considering the above scenario and give the answers of following questions:
1. Generate the college_details.csv and studentdetails.csv file. Make alteast 50 colleges
entries and 5000 students data. [Marks: 05]
2. Give rank to the students so that admission process will be performed in proper
sequence. Use any mechanism to give rank to the students. [Marks: 05]
3. Generate the choice filling CSV file for first 200 students and try to give them
admission in their preferable college and branch. Every day, the admission process of
200 students is carried out by the system. [Marks: 10]
4. At the end of first day admission process, generate day1_college_status.csv file, which
has a details of available seats in all the colleges that will available for admission
process on day 2. Perform the step 3 and step 4 iteratively until entire admission
process get over. [Marks: 10]
5. If any students did not get any admission as per choice on particular day, generate the
choice details one more time based on the available seats which execute on next day.
[Marks: 05]
6. Once all the admission process is complete, give the status of colleges and show in table that how many seat remain vacant in each branch of college. [Marks: 05]

ANS:
1.) open(create) csv file
    define object writer
    use for loop
    define null list li
    generate random college code and marks and append them in list
    append college code in another list cc for further use
    use writerow to write the list in csv file
2.) Read csv file using pandas
    calculate the total marks of every student
    Use sort_values in total and enrollment no. (Enrollment no only if total is same)
    Add rank column and give rank using .rank()
3.) open(create) csv file called choice_filling
    use for loop 
    append Enrollmentno in list li
    take random college code from list cc made before and random branch from list branch
    append it in list li
    use writerow to write the list in csv file choice_filling
    (The choice_filling file will be edited in every round(or every time the loop runs))
    .
    Open csv file in read mode
    Read lines using for loop(skip first line as it has the headings)
    Separate the choice to college code and branch
    read file college_details using pandas
    find the number of seats and decrease them by 1
    Edit the college_details file
4.) Copy college_details.csv to day1_college_status.csv 
    use for loop from range 0 to ((length of studentdetails.csv)/200) as that is the no. of rounds that should happen for all the students to get admitted 
    define a variable day for the name of Day(day)_ college_status.csv
5.) Add if condition 
    Add the value of Eno(Enrollmentno) in NewEno
    change the value of flag 
    so in next round NewEno will be considered
6.) read college_details.csv file through pandas
    show the dataframe

In [3]:
#Swara Patel
#18BCE172
#Sessional-Examination Assignment


import csv
import random
import pandas as pd

cc=[]

#question1

#college_details
with open('college_details.csv', 'w',newline='') as file1:    #open(create) college_details.csv
    writer=csv.writer(file1)
    writer.writerow(["CollegeCode","CSE","IT","ME","EE","EC","IC","CH","Civil","Auto"])
    seat=[0 ,60 ,120 ,180 ,240 ]                  #no. of seats allowed
    for i in range (0,50):
        li=[]
        a=random.sample(range(1,9999),1)     #random four digit number in college code
        str1="C"+"{0:04d}".format(a[0])      #college code
        cc.append(str1)                      #list of college code 
        li.append(str1)                      
        for i in range (0,9):
            s=random.choice(seat)            #no. of seats from list-seat
            li.append(s)
        writer.writerow(li)

        
#studentdetails
with open("studentdetails.csv","w",newline="") as file2:                    #open(create) studentdetails file
    writer=csv.writer(file2)                                                
    writer.writerow(["Enrollmentno","sub1","sub2","sub3","sub4","sub5"])
    for i in range (0,5000):
        li=[]
        a=random.sample(range(1,9999),1)                                    #random four digit number in college code
        str1="E"+"{0:04d}".format(a[0])                                     #student id
        li.append(str1)
        s=0
        for i in range (0,5):
            m=random.randint(40,100)                                        #40<marks<100 
            li.append(m)
        writer.writerow(li)


#question2
data=pd.read_csv("studentdetails.csv")

#totalmarks
Total=pd.Series([])
for i in range (0,len(data)):
    Total[i]=data["sub1"][i]+data["sub2"][i]+data["sub3"][i]+data["sub4"][i]+data["sub5"][i]
data.insert(6,"Total",Total)       #insert a column data

#Sorting
data.sort_values(["Total","Enrollmentno"], axis=0, ascending=False, inplace=True)      

#rank
rank=pd.Series([])
data["Rank"]=data["Total"].rank(method="min", ascending=False)
readsd=csv.reader(open("studentdetails.csv","r"))


#question3 and 4
day=1                            #file name-Day(day)_college_status
ran=int(len(list(readsd))/200)
flag=0                           #for question5
for j in range (0,ran):
    branch=["CSE","IT","ME","EE","EC","IC","CH","Civil","Auto"]
    with open("choice_filling.csv","w",newline="") as file3:           #open(create) choice filling file
        writer=csv.writer(file3)
        writer.writerow(["Enrollmentno","choice1","choice2","choice3","choice4","choice5","choice6","choice7","choice8","choice9","choice10"])     #header
        for i in range(0,200):
            #question5
            if flag==1:
                Newli=[]
                Newli.append(NewEno)
                for j in range(0,10):
                    Newccode=random.choice(cc)        #random selection of college code from list-cc
                    Newch=random.choice(branch)       #random choice of branch from list-branch
                    Newstr1=Newccode+"-"+Newch              #final choice
                    Newli.append(Newstr1)
                    writer.writerow(Newli)
                    flag=0
            li=[]
            df=pd.DataFrame(data)
            a=str(df.iloc[i:i+1,0:1])   #print(a):Enrollmentno      0       C0404                                        
            a1=a[-5:]                   #Enrollment no. of first student
            li.append(a1)
            for j in range(0,10):
                ccode=random.choice(cc)        #random selection of college code from list-cc
                ch=random.choice(branch)       #random choice of branch from list-branch
                str1=ccode+"-"+ch              #final choice
                li.append(str1)                
            writer.writerow(li)
    with open("choice_filling.csv","r") as file3:
        reader=csv.reader(file3)
        i=0
        for row in reader:
            if i>0:
                noseat=0
                s=1
                Eno=row[0][:5]                #Enrollmentno
                while noseat==0:
                    #question5
                    if noseat>10:
                        NewEno=Eno
                        flag=1
                        continue;
                    clg=row[s][0:5]           #collegecode
                    choice=row[s][6:]         #branch
                    df=pd.read_csv("college_details.csv")
                    noseat=int(df.loc[df["CollegeCode"]==clg,choice])      #no of seats  
                    s=s+1
                #print(noseat)
                #print(choice)
                a=str(df.loc[df["CollegeCode"]==clg,choice])               #a,a1 is used to find a2 i.e. no. of seats in branch               
                a1=a.splitlines()
                #print(a1)
                #print(a1[0][-3:])
                a2=int(a1[0][-3:])-1                                      #a2=no. of seats in branch, -1 as that seat gets allotted
                df.loc[df["CollegeCode"]==clg,choice]=a2                  #Updating Data 
                df.to_csv("college_details.csv",index=False)              #Adding Updated data in the file
            i=i+1
    reader=csv.reader(open("college_details.csv","r"))
    
    filename="Day{0}_college_status.csv".format(day)                    
    #print(filename)
    with open(filename,"w",newline="") as file:
        writer=csv.writer(file)                                           #Copying college_details to Day[i]_college_status
        for row in reader:
            writer.writerow(row)
    day=day+1
    
    
#question6
clgdata=pd.read_csv("college_details.csv")
clgdata

   CollegeCode  CSE   IT   ME   EE   EC   IC   CH  Civil  Auto
0        C4259  227   47  110  219   52   44  105     98   229
1        C0505  104   48   99    0   50  169  220    224    43
2        C2724   48   52   48   44  164  166   46    225   167
3        C5852  167   48  227    0    0  110   47      0     0
4        C8982  107  166  161    0    0  165  166    107    47
5        C1267   46  172    0  101  222   42   52    228     0
6        C2401  112   46   52    0  228  103  230      0   221
7        C2752   48    0  164    0   42  106  105    171   166
8        C5390   50   48   41  105    0    0  223    225   162
9        C1695  171   48    0  218  105    0    0      0   167
10       C8174   46   44  113  163   54  160   46     97     0
11       C4226  227   42  234   41  112    0  166      0    41
12       C9368    0  107   47  101    0    0   45    229     0
13       C8597  104   41  162  170   46  108   45    226   167
14       C7702  102  231   45  103    0  225   47    228     0
15       C2541  105  167  225  164    0  113   49     48    46
16       C0022   36  169  167   98  230    0  171    104   113
17       C5670    0  105  225  111   44   51    0    106     0
18       C0529  226  234    0   49  110  109  106    167   230
19       C8839  101   45    0    0  228   45  224    100   161
20       C8927  229  226   43  103  168  164  162     50   225
21       C0881  170  162   50  166    0  225   48    158   224
22       C6066    0  224   49    0  226  164    0    105   224
23       C1607    0   50  230    0   44  223   48    222   231
24       C3334  223  166  103    0  104   47  100    162    99
25       C6809  171    0    0  103    0    0  230      0     0
26       C6785  167  226   49  111  102  169  165    104   104
27       C3169   40   98  107    0    0   49  227      0   170
28       C4629   42  168  162  227    0  161   43    227    40
29       C4956    0  168    0    0    0    0  111    170   229
30       C6268   41  109  225  231  171  103    0    108   229
31       C0377  226    0  230   42    0  104   53    225   104
32       C0763  225   51    0  167   42    0   42    171    37
33       C9734    0   48  225  165   51    0  171    103   221
34       C9424  163  163  106    0  100   44  231    168   163
35       C1791  231  169    0    0  223  226  163    224   159
36       C6049  225   51    0    0  104  110  161      0   100
37       C3652  161   48  111  229    0  167  227     44    45
38       C9208  221  109   41    0    0  108  163    228   223
39       C8683  164  231    0   96  228    0  113    107   100
40       C4878  104  108   42    0  222  110    0      0    50
41       C1605    0    0   44  163    0  108  161      0   213
42       C3584    0  228  226  111   50   47  161    164   223
43       C7767  164   51   43    0  169  224  225      0   230
44       C5374  227  229  168   47  168    0  227      0    47
45       C3941  109   42  108    0  225  174  167      0   165
46       C1130   45  102  172  157  164    0   46     48   225
47       C5472    0  164  107   49  107    0   44    169     0
48       C8214    0  110  108    0  106  224  103    219     0
49       C6725  224   51  165   42   37  108  167    224    51